name: Paresh Mhetre's Blog
description: >
    
about: >
    Business Intelligence enthusiast.

master_repo: false
url: "http://mparesh.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           
  avatar:         https://raw.githubusercontent.com/Mparesh/mparesh.github.io/master/asset/IMG.jpg
  email:          "pareshmhetre@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: PareshMhetre
  github: https://github.com/Mparesh
  stackexchange:
  linkedin: https://www.linkedin.com/in/paresh-mhetre-16939198/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
