name:
description: >
    
about: >
    Analyst with experience in IT Service Management and worked extensively on monitoring and reporting processes varying from Telecom, Cloud infrastructure to Identity Access Management. I post here about my simple learnings and fun projects. I also occasaionaly write on personal blog : [https://pareshmhetre.wordpress.com/](https://pareshmhetre.wordpress.com/)

master_repo: false
url: "https://mparesh.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           
  avatar:         https://raw.githubusercontent.com/Mparesh/mparesh.github.io/master/asset/IMG.jpg
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter: PareshMhetre
  github:
  stackexchange:
  linkedin: https://www.linkedin.com/in/paresh-mhetre-16939198/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
